### ISSUE TITLE
Can not unzip after downloaded

### ISSUE THREAD

**Issue by Karen0103** [twelveand0/alphadiff-dataset#3]
I use git lfs clone to download but Error occurs when unzip the dataset.zip.

<img width="420" alt="screen shot 2018-10-17 at 2 05 12 pm" src="https://user-images.githubusercontent.com/16543224/47106876-bbb2bf00-d215-11e8-9abc-adf6eb27a220.png">

**Comment by twelveand0** [comment]
Hello, @Karen0103 , did you download the other files, such as dataset.z01~09? I split the whole dataset into multi-part Zip files, because GitHub has set a size limit for a single file. You should download all dataset.z* files to unzip it. 
If you still have problem with it, please let me know. And thanks for your interest in our work.

**Comment by Karen0103** [comment]
Hi, thanks for your reply.
I tried on Mac but it doesn't work. When I unzip on Windows, somehow I can unzip it.

**Comment by twelveand0** [comment]
I am sorry for this. I'm going to try by myself and then reply to you.

**Comment by twelveand0** [comment]
Hi, I tried on Linux (ubuntu 16.04 x86 ) with ZIP 3.0. In order to unzip it, I executed the following command.
```
>> cat dataset.z01 dataset.z02 dataset.z03 dataset.z04 dataset.z05 dataset.z06 dataset.z07 dataset.z08 dataset.z09 dataset.zip > complete.zip
>> unzip complete.zip
>> unzip data.zip
```
Because I don't have Mac, I can't try. I think it should be similar with Linux OS. The key step is to concatenate the part dataset.z* files together in order into a complete ZIP file. 

I also tried it on Windows, as you said, it can be unzipped.

**Comment by Karen0103** [comment]
Thank you so much! You are so kind. It helps a lot and I will try on Mac again.

**Comment by Rroscha** [comment]
> Thank you so much! You are so kind. It helps a lot and I will try on Mac again.

Hi, do you still have zip files of this dataset? If you still have this dataset now, I wonder if you could share it with us? I tried to download the datasets through git but got an error of "over data quota".

Thank you.
